services:
  fabric-webui-ts:
    image: tailscale/tailscale:latest
    hostname: fabric-webui
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    volumes:
      - ${PWD}/tailscale/ts-config:/config
      - ${PWD}/tailscale/ts-state:/var/lib/tailscale
    dns:
      - 100.100.100.100
      - 8.8.8.8
    restart: unless-stopped

  fabric-webui-app:
    image: pruth/fabric-webui:latest
    network_mode: service:fabric-webui-ts
    volumes:
      - fabric_storage:/fabric_storage
    environment:
      - FABRIC_CONFIG_DIR=/fabric_storage/.fabric_config
      - FABRIC_STORAGE_DIR=/fabric_storage
      - HOME=/tmp
    restart: unless-stopped

volumes:
  fabric_storage:
