services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - fabric_storage:/fabric_storage
    environment:
      - FABRIC_CONFIG_DIR=/fabric_storage/.fabric_config
      - FABRIC_STORAGE_DIR=/fabric_storage
      - HOME=/tmp
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "10000:3000"
    depends_on:
      - backend
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped

volumes:
  fabric_storage:
